version: "3"

services:
  discord:
    build: "."
    volumes:
    - "./src:/usr/src/app/src"
    env_file:
    - ./.env.dev
    depends_on:
    - mongo

  mongo:
    image: mongo
    env_file:
    - ./.env.dev
    ports:
    - "27020:27017"